# Generated by Django 2.0.3 on 2018-04-15 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("timelapse_manager", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover_of_streams",
                to="timelapse_manager.Image",
            ),
        )
    ]
