# Generated by Django 2.1.1 on 2018-09-29 15:26

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse_manager', '0003_auto_20180929_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagtimerange',
            options={'ordering': ('at',)},
        ),
        migrations.RemoveField(
            model_name='tagtimerange',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='tagtimerange',
            name='start_at',
        ),
        migrations.AddField(
            model_name='tagtimerange',
            name='at',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=None),
            preserve_default=False,
        ),
    ]
