version: "2"
services:
    docs:
        build: "."
        ports:
            - "8040:8000"
        command: "sphinx-autobuild --poll --host 0.0.0.0 --port 8000 . ./_build/html"
        volumes:
            - ".:/home/docs/docs:delegated"
